# Generated by Django 4.1.5 on 2023-01-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.IntegerField(primary_key=True, serialize=False)),
                ("category_title", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("gender", models.TextField()),
                ("login", models.TextField()),
                ("email", models.TextField()),
                ("date_register", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("date_create", models.DateField()),
                ("content", models.TextField(max_length=140)),
                (
                    "post_author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="just_app.users"
                    ),
                ),
                (
                    "post_category_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="just_app.category",
                    ),
                ),
            ],
        ),
    ]
