# Generated by Django 4.1.5 on 2023-01-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("just_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_category_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="just_app.category",
            ),
        ),
    ]
