# Generated by Django 4.1.5 on 2023-01-07 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("just_app", "0002_alter_post_post_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="login",
            field=models.CharField(
                max_length=25,
                validators=[
                    django.core.validators.RegexValidator(
                        message="He корректно введен логин!",
                        regex="(?=\\d*)(?=[a-z]*)(?=[A-Z]*).{6,10}$",
                    )
                ],
            ),
        ),
    ]
