# Generated by Django 4.1.5 on 2023-01-07 18:20

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("just_app", "0006_alter_users_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="login",
            field=models.CharField(
                max_length=25,
                validators=[
                    django.core.validators.RegexValidator(
                        code="Invalid login",
                        flags=re.RegexFlag["IGNORECASE"],
                        inverse_match=False,
                        message="He корректно введен логин!",
                        regex="^[a-zA-Z0-9]{6}$",
                    )
                ],
            ),
        ),
    ]
