# Generated by Django 4.1.5 on 2023-01-07 18:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("just_app", "0007_alter_users_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.TextField(
                max_length=50,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Enter correct email!"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="login",
            field=models.CharField(
                max_length=25,
                validators=[
                    django.core.validators.RegexValidator(
                        code="Invalid login",
                        flags=re.RegexFlag["IGNORECASE"],
                        inverse_match=False,
                        message="Login entered incorrectly!",
                        regex="^[a-zA-Z0-9]{6,25}$",
                    )
                ],
            ),
        ),
    ]
